export const CUSTOMER_PAYMENTS = "CUSTOMER_PAYMENTS";
export const CUSTOMER_PAYMENTS_SUCCESS = "CUSTOMER_PAYMENTS_SUCCESS";
export const CUSTOMER_PAYMENTS_FAIL = "CUSTOMER_PAYMENTS_FAIL";
export const ADD_CUSTOMER_PAYMENT = "ADD_CUSTOMER_PAYMENT";
export const CLEAN_CUSTOMER_PAYMENTS = "CLEAN_CUSTOMER_PAYMENTS";
