export const FETCH_LEDGER = "FETCH_LEDGER";
export const FETCH_LEDGER_SUCCESS = "FETCH_LEDGER_SUCCESS";
export const FETCH_LEDGER_FAIL = "FETCH_LEDGER_FAIL";
export const CLEANUP_LEDGER = "CLEANUP_LEDGER";
