export const FETCH_CUSTOMER_ORDERS = "FETCH_CUSTOMER_ORDERS";
export const FETCH_CUSTOMER_ORDERS_SUCCESS = "FETCH_CUSTOMER_ORDERS_SUCCESS";
export const FETCH_CUSTOMER_ORDERS_FAIL = "FETCH_CUSTOMER_ORDERS_FAIL";
