export const BLOCK_CUSTOMER = "BLOCK_CUSTOMER";
export const BLOCK_CUSTOMER_SUCCESS = "BLOCK_CUSTOMER_SUCCESS";
export const BLOCK_CUSTOMER_FAIL = "BLOCK_CUSTOMER_FAIL";
export const UNBLOCK_CUSTOMER = "UNBLOCK_CUSTOMER";
export const UNBLOCK_CUSTOMER_SUCCESS = "UNBLOCK_CUSTOMER_SUCCESS";
export const UNBLOCK_CUSTOMER_FAIL = "UNBLOCK_CUSTOMER_FAIL";
export const SET_CUSTOMER_DETAIL = "SET_CUSTOMER_DETAIL";
export const CLEANUP_CUSTOMER = "CLEANUP_CUSTOMER";
