export const FETCH_CUSTOMER_ORDERS = "FETCH_CUSTOMER_ORDERS";
export const FETCH_CUSTOMER_ORDERS_SUCCESS = "FETCH_CUSTOMER_ORDERS_SUCCESS";
export const FETCH_CUSTOMER_ORDERS_FAIL = "FETCH_CUSTOMER_ORDERS_FAIL";
export const CLEANUP_CUSTOMER_ORDERS = "CLEANUP_CUSTOMER_ORDERS";
export const SET_CUSTOMER = "SET_CUSTOMER";
export const ADD_CUSTOMER_ORDER = "ADD_CUSTOMER_ORDER";
