export const BLOCK_USER = "BLOCK_USER";
export const BLOCK_USER_SUCCESS = "BLOCK_USER_SUCCESS";
export const BLOCK_USER_FAIL = "BLOCK_USER_FAIL";
export const UNBLOCK_USER = "UNBLOCK_USER";
export const UNBLOCK_USER_SUCCESS = "UNBLOCK_USER_SUCCESS";
export const UNBLOCK_USER_FAIL = "UNBLOCK_USER_FAIL";
export const CLEANUP_USER = "CLEANUP_USER";
